import { collection, getDocs, limit, query, where } from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import BrandCard from "../../components/BrandCard";
import ProductCard from "../../components/ProductCard";
import { firebasefb } from "../../firebaseconfig";
import HomeLayout from "../../layouts/HomeLayout";

function Subcategory() {
  const navigate = useRouter();
  const {
    slug: [catid, subcat],
  } = navigate.query;
  //  const [catid, subcat] = slug;
  const [brands, setbrands] = useState([]);
  const [loading, setloading] = useState(true);
  const [pros, setpros] = useState([]);

  useEffect(() => {
    const sc = subcat.replaceAll("_", " ");

    const getBrand = new Promise(async (resolve) => {
      const q = query(
        collection(firebasefb, "brand"),
        where("catId", "==", catid),
        where("subcategory", "==", sc),
        limit(20)
      );
      const result = await getDocs(q);
      var a = [];
      result.docs.forEach((res) => a.push(res.data()));
      setbrands(a);
      return resolve();
    });
    const getProduct = new Promise(async (resolve) => {
      const q = query(
        collection(firebasefb, "product"),
        where("catId", "==", catid),
        where("subcategory", "==", sc),
        limit(20)
      );
      const result = await getDocs(q);
      var a = [];
      result.docs.forEach((res) => a.push(res.data()));
      setpros(a);
      return resolve();
    });

    Promise.all([getBrand, getProduct]).then((res) => {
      console.log("calling subcategory page");
      setloading(false);
    });
  }, [catid, subcat]);

  if (loading)
    return (
      <div className="h-screen flex items-center justify-center">
        <i className="fas fa-spinner animate-spin"></i>
      </div>
    );
  else
    return (
      <>
        <Head>
          <title>MyRevue - </title>
          <meta name="description" content="Generated by create next app" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />
          <script
            src="https://kit.fontawesome.com/5039367dbf.js"
            crossorigin="anonymous"
          ></script>
        </Head>
        <main>
          <div className="p-1 bg-black text-white min-h-screen">
            <p className="text-3xl py-1 border-b border-gray-500">
              {subcat.replaceAll("_", " ")}
            </p>
            <div className="">
              <p className="text-xl ">Brands</p>
              <div className="flex flex-wrap gap-1 items-center justify-center">
                {brands.map((br, index) => (
                  <BrandCard key={index} brand={br} />
                ))}
              </div>
            </div>
            <div className="">
              <p className="text-xl">Products </p>
              <div className=" flex flex-wrap gap-2 justify-center items-center">
                {pros.map((pro, index) => (
                  <ProductCard key={index} product={pro} />
                ))}
              </div>
            </div>
          </div>
        </main>
      </>
    );
}

Subcategory.layout = HomeLayout;

export default Subcategory;
