import { doc, getDoc } from "firebase/firestore";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import BrandCard from "../components/BrandCard";
import ProductCard from "../components/ProductCard";

import { firebasefb } from "../firebaseconfig";
import HomeLayout from "../layouts/HomeLayout";

function UserHome() {
  let navigate = useRouter();
  const [top, settop] = useState(null);

  useEffect(() => {
    if (top) return;
    getDoc(doc(firebasefb, "top", "top")).then((res) => {
      console.log(res, "this is data we are getting from ");
      console.log(res.data());
      settop(res.data());
    });
  }, []);

  console.log(top);
  const navigatePage = (page) => {
    navigate.push(page);
  };

  if (!top)
    return (
      <div className="h-screen flex items-center justify-center">
        <i className="fas fa-spinner animate-spin"></i>
      </div>
    );

  return (
    <>
      <Head>
        <title>MyRevue</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <script
          src="https://kit.fontawesome.com/5039367dbf.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <div className="text-white">
        <img
          className=" border w-full rounded-md h-96"
          src={top.branding}
          alt=""
        />
        <div className="bg-white bg-opacity-10 px-6 py-3 rounded-2xl mt-10">
          <h1 className="text-3xl font-bold my-4 mb-8">Featured Brands</h1>
          <div className="mb-10 flex gap-5 flex-wrap">
            {top?.topBrands.map((brand, index) => (
              <BrandCard brand={brand} key={index} />
            ))}
          </div>
        </div>

        <div className=" mt-10 px-6 py-3 rounded-2xl">
          <h1 className="text-3xl font-bold mb-8 ">Top Products</h1>
          <div className=" flex flex-wrap gap-4">
            {top?.topProducts.map((pro, index) => (
              <ProductCard key={index} product={pro} />
            ))}
          </div>
        </div>

        <div className=" mt-10 px-6 py-3 rounded-2xl">
          <h1 className="text-3xl font-bold mb-8">Top Reviewers</h1>
          <div className="mb-10 flex flex-wrap gap-5">
            {top?.top.map((revrs, index) => (
              <div key={index} className="">
                <div
                  onClick={() => navigatePage("/profile/" + revrs.id)}
                  className=" p-4 flex flex-col items-center rounded-md overflow-hidden shadow-lg hover:scale-105 transition duration-500 cursor-pointer
							"
                >
                  <div className="h-24 w-24 rounded-full overflow-hidden border-2">
                    <img
                      src={revrs.imageUrl ?? "https://i.pravatar.cc/300"}
                      alt="Logo"
                    />
                  </div>
                  <p className=" font-light text-lg py-4">{revrs.name}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

UserHome.layout = HomeLayout;
export default UserHome;
