import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useStateValue } from "../StateProvider";
import { collection, getDocs, query, where } from "firebase/firestore";
import { firebasefb } from "../firebaseconfig";
import { getAuth } from "firebase/auth";
import Link from "next/link";
import Category from "../components/Category";

export default function Home() {
  const [{ user, category }, dispatch] = useStateValue();
  const [cats, setcats] = useState([]);
  const [loading, setloading] = useState(true);

  useEffect(() => {
    console.log(category.length, "this is category");
    if (category.length !== 0) {
      setcats(category);
      setloading(false);
      return;
    }
    const q = query(collection(firebasefb, "category"));
    getDocs(q).then((res) => {
      var a = [];
      res.docs.forEach((ca) => {
        a.push(ca.data());
      });
      dispatch({
        type: "SET_CATEGORY",
        category: a,
      });
      setcats(a);
      setloading(false);
    });
  }, []);

  console.log(loading, category);

  const logout = () => {
    dispatch({ type: "DELETE_USER" });
    const auth = getAuth();
    auth.signOut();
  };

  if (loading)
    return (
      <div className="h-screen flex items-center justify-center">
        <i className="fas fa-spinner animate-spin"></i>
      </div>
    );
  else
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link
            href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />
          <script
            src="https://kit.fontawesome.com/5039367dbf.js"
            crossorigin="anonymous"
          ></script>
        </Head>
        <main>
          <div className=" bg-black flex h-screen">
            <div className="w-56">
              <div className=" border-r border-gray-800 bg-white bg-opacity-5 p-1 z-0 fixed h-screen top-0 w-56 overflow-y-auto hide-scroll">
                <div className=" flex my-3 justify-center">
                  <Link href="/">
                    <Image
                      className=" w-32 "
                      src="/logo.png"
                      alt="logo"
                      width="100px"
                      height="40px"
                    />
                  </Link>
                </div>
                <div className="h-screen text-gray-300 py-2 ">
                  <ul className=" pb-3 flex flex-col justify-center border-b border-gray-700 ">
                    <li className="py-3 hover:bg-white hover:bg-opacity-10 hover:text-gray-100 cursor-pointer text-lg  pl-4 ">
                      <Link href="/">
                        <p className="text-sm">
                          <i className="fas fa-home  pr-3 fa-lg  "></i>
                          Home
                        </p>
                      </Link>
                    </li>
                    <li className="py-3 hover:bg-white hover:bg-opacity-10 hover:text-gray-100 cursor-pointer text-lg pl-4">
                      <p className="text-sm">
                        <i className="fas fa-play  pr-3 fa-lg  "></i>
                        Experiences
                      </p>
                    </li>
                  </ul>

                  <p className=" pl-4 pt-3 text-xl">CATEGORIES</p>
                  <ul className=" py-4 border-b border-gray-700">
                    {cats.map((cat, index) => (
                      <Category cat={cat} key={index} />
                    ))}
                  </ul>

                  <ul className=" pb-3 flex flex-col justify-center border-b border-gray-700 text-sm ">
                    <li className="py-3 hover:bg-white hover:bg-opacity-10 hover:text-gray-100 cursor-pointer  font-thin pl-4">
                      <i className="fas fa-cog pr-4 fa-lg fa-fw"></i> Setting
                    </li>
                    <li className="py-3 hover:bg-white hover:bg-opacity-10 hover:text-gray-100 cursor-pointer  pl-4">
                      <i className="fas fa-question-circle pr-5 fa-lg fa-fw "></i>
                      Help
                    </li>
                    <li className="py-3 hover:bg-white hover:bg-opacity-10 hover:text-gray-100 cursor-pointer  pl-4">
                      <i className="fas fa-comment pr-5 fa-lg fa-fw"></i>{" "}
                      Feedback
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="flex-1">
              <div className="flex sticky z-10 top-0  bg-black border-b items-center h-16 shadow-lg p-2  border-gray-700">
                <div className="w-72"></div>
                <div className=" flex-1 flex items-center justify-center">
                  <i className="fas fa-search p-3 rounded-l-full text-gray-400 cursor-pointer bg-white bg-opacity-20  "></i>
                  <input
                    className="w-full bg-white bg-opacity-20 py-2 px-1 rounded-r-full outline-none appearance-none"
                    type="text"
                    placeholder="Type to Search"
                  />
                </div>
                <div className=" w-80 flex justify-end  items-center">
                  {user ? (
                    <Link href="/profile" className="flex items-center  mx-3">
                      <img
                        src={user.imageUrl}
                        alt=""
                        className="h-10 w-10 rounded-full"
                      />
                    </Link>
                  ) : (
                    <Link
                      href="/loginpage"
                      className="  hover:bg-gray-700 transform duration-200 rounded-xl p-2"
                    >
                      <p className="">
                        <i className="fas fa-user fa-lg px-1  "></i> Sign in
                      </p>
                    </Link>
                  )}
                  {user ? (
                    <button onClick={() => logout()}>Log Out</button>
                  ) : null}
                </div>
              </div>

              <div className="">
                {/* SideNav */}

                {/* Main body */}
                <div className=" p-4"></div>
              </div>
              {/* <Foot /> */}
            </div>
          </div>
        </main>
        <footer></footer>
      </div>
    );
}
